"""empty message

Revision ID: 22572a315ce4
Revises: 621c6779173f
Create Date: 2019-11-16 15:12:16.733398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22572a315ce4'
down_revision = '621c6779173f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
