"""empty message

Revision ID: 675bf6fe852d
Revises: 22572a315ce4
Create Date: 2019-11-16 15:23:34.823242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675bf6fe852d'
down_revision = '22572a315ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
